[package]
name = "rust-slackbot-llm"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["multipart", "json"] }
dotenvy = "0.15"
dotenvy_macro = "0.15"
serde = { version = "1" }
serde_json = "1"
axum = { version = "0.6", features = ["headers", "macros"] }
uuid = { version = "1.3", features = ["v4"] }
hmac = "0.12"
sha2 = "0.10"
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio"] }
bincode = "1.3"
futures = "0.3"
